### ISSUE TITLE
stream audio without a sound card

### ISSUE THREAD

**Issue by GoogleCodeExporter** [rafael2k/darkice#112]
```
What steps will reproduce the problem?
1.
2.
3.

What is the expected output? What do you see instead?
trying to use audio that is coming into a Raspberry PI2 running Fedora21 via a 
VOIP application. There really isn't any connected sound card. The application 
I am using provide for input and out put using a Logitech headset, But I don't 
want to stream the audio from the headset. The problem is that Darkice sees 
only the headset as sound card. I just want to stream the audio coming in from 
the internet.

Is it doable?

What version of the product are you using? On what operating system?
Darkice 1.0 on Fedora21

Please provide any additional information below.


```

Original issue reported on code.google.com by `FranMi...@gmail.com` on 21 Mar 2015 at 7:28

**Comment by sleeksorrow** [comment]
My way to do this is using pulseaudio with null-sink. Playing to the null sink and grabbing with darkice from null-sink monitor

**Comment by rafael2k** [comment]
Jack support is exactly for this.

**Comment by kazepis** [comment]
> Jack support is exactly for this.

Rafael could you point me to the right direction?
I have a VM without sound card and want to setup dark ice to stream from an mp3 folder to ice cast.
I can't find anything relevant online (google)
Thank you!

**Comment by kripton** [comment]
@kazepis: Did you set up a jack audio server / system before? If not, please read the relevant docs. A good overview can be found at: https://wiki.archlinux.org/index.php/JACK_Audio_Connection_Kit. Your Linux distribution inside the VM might also provide some information.
JACK requires one soundcard to work properly. However, you can select a "dummy" soundcard that has no inputs or outputs. Using such a setup, audio can still be routed between applications (from your audio player to darkice). How you "play" your MP3s (read the files, decode them and hand them over to JACK) you will have a choice of about 2000 options (mpd, mplayer, gstreamer, some graphical music player, ...)

**Comment by kazepis** [comment]
I’m new in this universe. I’ve never installed jack before. I will definitely look into the docs. Thank you very much. Btw I’m using Debian stable. Arecord -l and aplay -l don’t report any sound cards. I’ll look into it more.
