### ISSUE TITLE
Compile 1.2 produces errors

### ISSUE THREAD

**Issue by witchi** [rafael2k/darkice#114]
I tried to compile v1.2, but I get some errors:

In file included from OpusLibEncoder.cpp:42:0:
OpusLibEncoder.h: In member function ‘int OpusIdHeader::buildPacket(unsigned char**)’:
OpusLibEncoder.h:96:55: error: ‘malloc’ was not declared in this scope
OpusLibEncoder.h: In member function ‘int OpusCommentHeader::buildPacket(unsigned char**)’:
OpusLibEncoder.h:156:56: error: ‘malloc’ was not declared in this scope
OpusLibEncoder.cpp: In member function ‘virtual bool OpusLibEncoder::open()’:
OpusLibEncoder.cpp:164:42: error: ‘memset’ was not declared in this scope
OpusLibEncoder.cpp:219:40: error: ‘strncpy’ was not declared in this scope
OpusLibEncoder.cpp:242:38: error: ‘strlen’ was not declared in this scope
OpusLibEncoder.cpp:243:59: error: ‘malloc’ was not declared in this scope
OpusLibEncoder.cpp:248:52: error: ‘strncat’ was not declared in this scope
OpusLibEncoder.cpp:295:25: error: ‘free’ was not declared in this scope
OpusLibEncoder.cpp: In member function ‘virtual unsigned int OpusLibEncoder::write(const void*, unsigned int)’:
OpusLibEncoder.cpp:365:58: error: ‘memset’ was not declared in this scope
OpusLibEncoder.cpp:369:65: error: ‘memcpy’ was not declared in this scope
OpusLibEncoder.cpp:428:50: error: ‘memset’ was not declared in this scope
OpusLibEncoder.cpp:448:42: error: ‘memcpy’ was not declared in this scope
OpusLibEncoder.cpp: In member function ‘virtual void OpusLibEncoder::flush()’:
OpusLibEncoder.cpp:480:32: error: ‘memset’ was not declared in this scope
OpusLibEncoder.cpp: In member function ‘virtual void OpusLibEncoder::close()’:
OpusLibEncoder.cpp:558:21: error: ‘stderr’ was not declared in this scope
OpusLibEncoder.cpp:558:61: error: ‘fprintf’ was not declared in this scope
make[2]: *** [OpusLibEncoder.o] Error 1

Any ideas, what is missing?
Thanks
Andre

**Comment by witchi** [comment]
I have added in FaacEncoder.cpp on line 281:

#include <cstring>

and in file OpusLibEncoder.h on line 43:

#include <cstdlib>
#include <cstring>
#include <cstdio>

After these changes, the tool has been built without any errors.

**Comment by rafael2k** [comment]
Fixed in 1.3 release.
