### ISSUE TITLE
Request for new release containing fixes related to remote server streaming

### ISSUE THREAD

**Issue by paraenggu** [rafael2k/darkice#115]
It would be helpful and much appreciated if you could create a new release of darkice (1.2.1 maybe?) which contains 710d2c26c4f9518d2f382673bf8b1829b9bdac3d

Afterwards, I'm able to bump the [ darkice CentOS RPM](https://build.opensuse.org/package/show/home:radiorabe:streambox/darkice) without having to apply patches and hope that my Opus remote streaming problem is gone.

**Comment by rafael2k** [comment]
Done. 1.3 released.

**Comment by paraenggu** [comment]
Wow, that was fast, thank you very much!
