### ISSUE TITLE
Release for Shoutcast Fix

### ISSUE THREAD

**Issue by Sonictherocketman** [rafael2k/darkice#142]
Hey Devs!

I saw that v1.3 has an issue with streaming to Shoutcast servers and I think I'm running into it. AFAIK the isn't released yet. Is there a timeline for a release (~v1.3.1 or v1.4)?

If not, can you give me any tips on reverting to v1.2? I've checked the rpm repos, but they seem to only have v1.3 for my version of Debian, and I'm unsure how to compile/install the dev version.

------

P.S. As an OSS maintainer myself, I'm astonished and amazed that this project has been around and active for 18 years. Keep it up!

**Comment by rafael2k** [comment]
1.4 out!
; )
