### ISSUE TITLE
darkice crashing upon startup

### ISSUE THREAD

**Issue by joe-death** [rafael2k/darkice#147]
DarkIce crashed at like 2am last night. Crashes on startup now. If theres somewhere else i need to look in logs, please enlighen, as I cant find anything except the cli display and journal

darkice.service - LSB: Live audio streamer

Loaded: loaded (/etc/init.d/darkice; generated; vendor preset: enabled)

Active: active (exited) since Mon 2019-04-29 06:13:34 EDT; 10s ago

Docs: man:systemd-sysv-generator(8)

Process: 1258 ExecStop=/etc/init.d/darkice stop (code=exited, status=0/SUCCESS

Process: 1296 ExecStart=/etc/init.d/darkice start (code=exited, status=0/SUCCE

CGroup: /system.slice/darkice.service

Apr 29 06:13:34 pi2 systemd[1]: Starting LSB: Live audio streamer...

Apr 29 06:13:34 pi2 systemd[1]: Started LSB: Live audio streamer.

yoder@pi2:~/op25/op25/gr-op25_repeater/apps $ sudo service darkice status● darkice.service - LSB: Live audio streamer

Loaded: loaded (/etc/init.d/darkice; generated; vendor preset: enabled)

Active: active (exited) since Mon 2019-04-29 06:13:34 EDT; 15s ago

Docs: man:systemd-sysv-generator(8)

Process: 1258 ExecStop=/etc/init.d/darkice stop (code=exited, status=0/SUCCESS

Process: 1296 ExecStart=/etc/init.d/darkice start (code=exited, status=0/SUCCE

CGroup: /system.slice/darkice.service

Apr 29 16:46:31 pi2 darkice[25664]: Copyright (c) 2000-2007, Tyrell Hungary, http://tyrell.hu/

Apr 29 16:46:31 pi2 darkice[25664]: Copyright (c) 2008-2013, Akos Maroy and Rafael Diniz

Apr 29 16:46:31 pi2 darkice[25664]: This is free software, and you are welcome to redistribute it

Apr 29 16:46:31 pi2 darkice[25664]: under the terms of The GNU General Public License version 3 or

Apr 29 16:46:31 pi2 darkice[25664]: any later version.

Apr 29 16:46:31 pi2 darkice[25664]: Using config file: /etc/darkice-stream0.cfg

Apr 29 16:46:31 pi2 darkice[25664]: Using ALSA DSP input device: loop0

Apr 29 16:46:31 pi2 darkice[25664]: Using POSIX real-time scheduling, priority 4

Apr 29 16:46:32 pi2 darkice[25664]: DarkIce: IceCast2.cpp:261: Icecast2 - Unexpected response from server [0]

Apr 29 16:46:32 pi2 systemd[1]: darkice-stream0.service: Main process exited, code=exited, status=255/n/a

Apr 29 16:46:32 pi2 systemd[1]: darkice-stream0.service: Unit entered failed state.

Apr 29 16:46:32 pi2 systemd[1]: darkice-stream0.service: Failed with result 'exit-code'.

Apr 29 16:46:37 pi2 systemd[1]: darkice-stream0.service: Service hold-off time over, scheduling restart.

Apr 29 16:46:37 pi2 systemd[1]: Stopped darkice-stream0.

**Comment by pardo-bsso** [comment]
@joe-death is the streaming server up and ok?

**Comment by joe-death** [comment]
I assume yes, its broadcastify

**Comment by joe-death** [comment]
Ok someone else suggested the same. Will open a ticket with them.

**Comment by pardo-bsso** [comment]
@joe-death any news on this?

**Comment by joe-death** [comment]
External fw was blocking port. Opened fw, issue fixed

**Comment by pardo-bsso** [comment]
Glad it worked. Could you please close the issue?
