### ISSUE TITLE
Darkice v1.4 - Missing configure script

### ISSUE THREAD

**Issue by paraenggu** [rafael2k/darkice#148]
First, thanks a lot for the new Darkice v1.4 release @rafael2k!

While trying to build the new release, I noticed that the `configure` script is missing and must be generated with the help of `autoreconf -i` beforehand.

Would it be possible to re-ship the generated `configure` script within new release tarballs as it was the case with older ones?

Thanks a lot!

**Comment by rafael2k** [comment]
Please check now. Reopen the issue if you find something else.

**Comment by paraenggu** [comment]
Thank you @rafael2k! Everything looks good, `autoreconf` isn't necessary anymore.
