### ISSUE TITLE
DarkIce: IceCast2.cpp:251: Icecast2 - wrong password [0]

### ISSUE THREAD

**Issue by 0d0a** [rafael2k/darkice#154]
1.3 works with same credentials for icecast2 server...
found the mistake!!!!

password line MUST NOT contain anything but password... no # comment after password!!!!!!!

**Comment by petitnj** [comment]
The same is true for Darkice 1.4. The password must not have anything but 
password = xxxxxx
no comment.

**Comment by 0d0a** [comment]
exactly.

On reading petitnj's message i installed darkice 1.4 and run into the
same problem ...

**Comment by petitnj** [comment]
Yes, I removed the comments in the password line and ShoutCast from Darkice 1.4 works with listen2myradio.com

**Comment by petitnj** [comment]
Can we replace the 1.3 version that is in the Raspberry Pi module updates with the 1.4 that actually works? When doing an apt-get install darkice, the installed version doesn't work with ShoutCast (even with no comment on the password line. Thanks.

**Comment by 0d0a** [comment]
Isn’t that up to the deb maintainers?

the white rider
(Het leuke van ... is weten op reis te zijn
