### ISSUE TITLE
Can't use multiple "special characters" in password with multiple stream IDs

### ISSUE THREAD

**Issue by Laav** [rafael2k/darkice#161]
The last few days i've tested a few setups/configs to use **Darkice 1.4** with **SHOUTcast Server v2.5.5.733**, with 1 stream ID all is working fine without any problems.

With a seconds stream ID the problems start, most of the time Darkice won't connect to the server and gives an "AlsaDspSource :: Buffer overrun!" after some time (and goes on with this).

After some debugging i've found that there is still an issue how Darkice treats the 'Stream ID' field, with only 1 "special character" all is working fine but with more then 1 "special character" the connection for all the stream ID's fail.

I've tried multiple passwords, the ones with an **V** at the end **WORK** fine, the ones with an **X** at the end don't.

```
rooooot1EPC	V
rooooot11EPC	X
rooooot1@EPC	X
rooooot@EPC	V
rooooot@@EPC	X
roo@ooot@EPC	X
roo1ooot@EPC	X
roo1oootEPC	V
```

So all the passwords with only 1 special character (character or number) works fine, the other ones don't work.

**Comment by DanielEckl** [comment]
Just a theoretical thought without in-depth knowledge: I recognized that - except for the special chars - there is another pattern. All working passwords have 12 characters, while all failing ones have 13.
Maybe test again with just replacing characters and leaving the length at 12 chars to rule out that there is a character limit of 12 ;)

**Comment by Laav** [comment]
Thanks for the reply, tested a bunch of new passwords and the limit is 11 chars for the password and three extra for the stream-ID..

The whole thing is working now with 11 chars with a bunch of "special characters"; @ro3ot3!EPC (fake pass).

Maybe the problem is the password-length + :#1 for the stream ID?
