### ISSUE TITLE
code.google.com -> github.com

### ISSUE THREAD

**Issue by dgmltn** [rafael2k/darkice#163]
Hello, I noticed on my icecast monitor page that the darkice client mentions code.google.com, which led me here. Are you accepting PR's? I don't mind doing the work to update the references to code.google.com in this repo to their new location on github:

http://code.google.com/p/darkice -> https://github.com/rafael2k/darkice

**Comment by rafael2k** [comment]
Yes, accepting PRs.

**Comment by dgmltn** [comment]
Sorry, not using this project anymore
