### ISSUE TITLE
Darkice List is blocked in China

### ISSUE THREAD

**Issue by KPJ-qd** [rafael2k/darkice#174]
Please encourage freelist to change their reCAPTCHA provider. Registration can't be completed without a CAPTCHA, and they use the Google.com script. All google sites are blocked in China due to long-standing differences of opinion between the censors and Alphabet.

**Comment by KPJ-qd** [comment]
I'm just trying to get Darkice running. Could you explain how that's spam? I'd appreciate it.--Ken-------- Original message --------From: Christian Eichert ***@***.***>Date: Thu, Oct 14, 2021, 7:46 PMTo: rafael2k/darkice ***@***.***>Cc: KPJ-qd ***@***.***>, Author ***@***.***>Subject: Re: [rafael2k/darkice] Darkice List is blocked in China (#174)
spam

**Comment by rafael2k** [comment]
Send me your email, I think I can add you. Sorry for this.
