### ISSUE TITLE
compiling fails on raspberry pi bullseye 64 bit

### ISSUE THREAD

**Issue by 0d0a** [rafael2k/darkice#176]
message has something to do with the lame library, path not found.

**Comment by pardo-bsso** [comment]
Hi @0d0a!

Thanks for the bug report. That issue is most likely because you don't have either libmp3lame or its dev package.
Install these two and try again: `libmp3lame0 libmp3lame-dev`

Also, next time try to be more specific. While we have some intuition our scrying glasses are out of order.

**Comment by 0d0a** [comment]
Would be nice if following was added to the readme:
Debian and derivates: install libfaac following these steps for bullseye 
Add sources to sources.list
apt update
apt install debhelper
apt-get -b source libfaac0-dev
sudo dpkg -I libfaac_1.30_1_armhf.deb
sudo dpkg -i libfaac-dev_1.30-1_armhf.deb

For pulse 
sudo apt install libpulse-dev

For alsa
sudo apt install libasound2-dev

Regards

the white rider
(Het leuke van ... is weten op reis te zijn
