### ISSUE TITLE
darkice stops processing ALSA input and hangs

### ISSUE THREAD

**Issue by jacobmarble** [rafael2k/darkice#178]
Approximately once per 48 hours, darkice stops processing live input from an ALSA device, and quietly stops writing to the configured Icecast service. The only indication of failure is a log entry `DarkIce: AlsaDspSource.cpp:265: File descriptor in bad state [0]`.

The error appears to be the errno corresponding to `EBADFD`. With the help of some googling, It sounds like this error is not common, ad surfaces most commonly when a sounds driver misbehaves, and reaches a "bad state".

Restarting darkice rectifies the situation every time this happens (restarting Linux is not necessary). Since the error is likely not recoverable, it seems that the best course of action would be for the process to exit with a non-zero status code. This way, systemd (or any process manager) can log and restart the process automatically.

However, looking at the code (I'm not up on C++) it seems that the Exception does bubble all the way up to main.cpp line 162, which is followed by the end of `main()` -- why then, does the process hang, rather than exit? Perhaps because there are threads that have not yet joined?

I'll try making some small code changes to more gracefully handle the exception.

```
DarkIce 1.3 live audio streamer, http://code.google.com/p/darkice/
Copyright (c) 2000-2007, Tyrell Hungary, http://tyrell.hu/
Copyright (c) 2008-2013, Akos Maroy and Rafael Diniz
This is free software, and you are welcome to redistribute it
under the terms of The GNU General Public License version 3 or
any later version.
Using config file: /etc/darkice-kszt-ctaf.cfg
23-Jul-2022 14:00:50 Using ALSA DSP input device: plughw:1,0
23-Jul-2022 14:00:50 buffer size:  264600
23-Jul-2022 14:00:50 encoding
23-Jul-2022 14:00:50 Using POSIX real-time scheduling, priority 4
23-Jul-2022 14:00:51 HTTP/1.0 200
23-Jul-2022 14:00:51 set lame mode 3
23-Jul-2022 14:00:51 set lame channels 1
23-Jul-2022 14:00:51 set lame in sample rate 44100
23-Jul-2022 14:00:51 set lame out sample rate 44100
23-Jul-2022 14:00:51 set lame bit rate 16
23-Jul-2022 14:00:51 set lame quality 9
23-Jul-2022 14:00:51 set lame lowpass frequency 3500
23-Jul-2022 14:00:51 set lame highpass frequency 0
23-Jul-2022 14:00:51 set lame psycho acoustic model 1
23-Jul-2022 14:00:51 set lame error protection 1
LAME 3.100 32bits (http://lame.sf.net)
Using polyphase lowpass filter, transition band:  3023 Hz -  3556 Hz
23-Jul-2022 14:00:51 MultiThreadedConnector :: transfer, bytes 0
23-Jul-2022 14:00:51 MultiThreadedConnector :: ThreadData :: threadFunction, was (thread, priority, type):  0x1ed2780 4 SCHED_FIFO
23-Jul-2022 14:00:51 MultiThreadedConnector :: ThreadData :: threadFunction, now is (thread, priority, type):  0x1ed2780 1 SCHED_FIFO
DarkIce: AlsaDspSource.cpp:265: File descriptor in bad state [0]
```

**Comment by jacobmarble** [comment]
For context, the ALSA device is a USB sound card connected to a Raspberry Pi 2B running Debian 11. I use this USB device because it is the only USB device I'm aware of with a proper "line-in" port.

`lsusb` reports:
```
Bus 001 Device 005: ID 0d8c:0102 C-Media Electronics, Inc. CM106 Like Sound Device
```

**Comment by DanielEckl** [comment]
Another darkice user here. This error is most probably directly from alsa libraries that darkice is using. When searching for this message I can find many different alsa programs giving this error when there are issues with audio device or kernel drivers.
While I cannot give any direct hints for fixing this, I suggest that you first check if the issue is in alsa or in darkice, like trying to capture audio from the soundcard with arecord for example. Most probably this will run into the same issue if it's an alsa problem.
Also it might be that you have chosen bitrates or channels in darkice config that your sound device cannot provide. Maybe try different values. Also verify that you really have configured the correct capture device.

**Comment by jacobmarble** [comment]
@DanielEckl I agree that the bug that triggers the error is likely in the device driver or in ALSA itself. However, I'm proposing that darkice should handle the error gracefully. If I can patch darkice to do that, then I'll open a PR.

**Comment by DanielEckl** [comment]
I'm sorry somehow I skipped most of the text you wrote above your log, where you basically already said everything I did in my answer. I blame it to the heat in my office.

**Comment by jacobmarble** [comment]
:) no worries @DanielEckl 

From the [ALSA docs](https://www.alsa-project.org/alsa-doc/alsa-lib/pcm.html#pcm_errors):
> -EBADFD
>
> This error means that the device is in a bad state. It means that the handshake between application and alsa-lib is corrupted.

Darkice receives this error value from [ALSA's snd_pcm_readi()](https://www.alsa-project.org/alsa-doc/alsa-lib/group___p_c_m.html#ga4c2c7bd26cf221268d59dc3bbeb9c048):
> -EBADFD   PCM is not in the right state (SND_PCM_STATE_PREPARED or SND_PCM_STATE_RUNNING)

"not in the right state" sounds benign; maybe darkice can simply fix the state by reconnecting or similar? I'll try to figure out what the state is when -EBADFD is returned.

**Comment by jacobmarble** [comment]
The "bad state" or "not in the right state" is 19 (or -19, but it doesn't matter), according to my `println` style debugging. That's certainly not a good state, as the valid states are enumerated 0 through XXX in XXX.

Hacky debugging:
```diff
diff --git a/darkice/trunk/src/AlsaDspSource.cpp b/darkice/trunk/src/AlsaDspSource.cpp
index 7ef6a0c..dc7acb0 100644
--- a/darkice/trunk/src/AlsaDspSource.cpp
+++ b/darkice/trunk/src/AlsaDspSource.cpp
@@ -261,6 +261,10 @@ AlsaDspSource :: read (    void          * buf,
         }
     } while (ret == -EAGAIN);

+    if ( ret == -EBADFD ) {
+        throw Exception(__FILE__, __LINE__, snd_strerror(ret), std::to_string(snd_pcm_state(captureHandle)).c_str());
+    }
+
     if ( ret < 0 ) {
         throw Exception(__FILE__, __LINE__, snd_strerror(ret));
     }
```

Result of hacky debugging:
```console
Jul 26 23:29:15 lviv darkice[9972]: DarkIce: AlsaDspSource.cpp:265: File descriptor in bad state-19 [0]
```

ALSA state enum, which has nothing close to 19 (or -19) (I'm using ALSA 1.2.4):
```cpp
/** PCM state */
typedef enum _snd_pcm_state {
	/** Open */
	SND_PCM_STATE_OPEN = 0,
	/** Setup installed */ 
	SND_PCM_STATE_SETUP,
	/** Ready to start */
	SND_PCM_STATE_PREPARED,
	/** Running */
	SND_PCM_STATE_RUNNING,
	/** Stopped: underrun (playback) or overrun (capture) detected */
	SND_PCM_STATE_XRUN,
	/** Draining: running (playback) or stopped (capture) */
	SND_PCM_STATE_DRAINING,
	/** Paused */
	SND_PCM_STATE_PAUSED,
	/** Hardware is suspended */
	SND_PCM_STATE_SUSPENDED,
	/** Hardware is disconnected */
	SND_PCM_STATE_DISCONNECTED,
	SND_PCM_STATE_LAST = SND_PCM_STATE_DISCONNECTED,
	/** Private - used internally in the library - do not use*/
	SND_PCM_STATE_PRIVATE1 = 1024
} snd_pcm_state_t;
```

**Comment by jacobmarble** [comment]
> fix the whole issue for my own situation, where systemd is configured to restart the process until the end of time.

This change does exactly that. I had to learn what `_Exit()` does.

```diff
diff --git a/darkice/trunk/src/AlsaDspSource.cpp b/darkice/trunk/src/AlsaDspSource.cpp
index 7ef6a0c..70705e0 100644
--- a/darkice/trunk/src/AlsaDspSource.cpp
+++ b/darkice/trunk/src/AlsaDspSource.cpp
@@ -261,6 +261,11 @@ AlsaDspSource :: read (    void          * buf,
         }
     } while (ret == -EAGAIN);

+    if ( ret == -EBADFD ) {
+        _Exit(1);
+        //throw Exception(__FILE__, __LINE__, snd_strerror(ret), std::to_string(snd_pcm_state(captureHandle)).c_str());
+    }
+
     if ( ret < 0 ) {
         throw Exception(__FILE__, __LINE__, snd_strerror(ret));
     }
```

From the `_EXIT(2)` manpage:
```text
_exit, _Exit - terminate the calling process
...
_exit()  terminates the calling process "immediately".  Any open file descriptors belonging to the process are closed.  Any children of the process are inherited by init(1) (or by the nearest "subreaper" process as defined through the use of the prctl(2) PR_SET_CHILD_SUBREAPER operation).
...
In glibc up to version 2.3, the _exit() wrapper function invoked the kernel system call of the same name.  Since glibc 2.3, the wrapper function invokes exit_group(2), in order to terminate all of the threads in a process.  (The raw _exit() system call terminates only the calling thread.)
```

**Comment by jacobmarble** [comment]
From my logs, this demonstrates that systemd successfully handles the process restart. Notice the adjacent lines at timestamps 03:39:14 and 03:39:31, indicating a fairly quick recovery.

```text
Jul 29 02:34:19 lviv darkice[14297]: Using polyphase lowpass filter, transition band:  3023 Hz -  3556 Hz
Jul 29 02:34:19 lviv darkice[14297]: 29-Jul-2022 02:34:19 MultiThreadedConnector :: transfer, bytes 0
Jul 29 02:34:19 lviv darkice[14297]: 29-Jul-2022 02:34:19 MultiThreadedConnector :: ThreadData :: threadFunction, was (thread, priority, >
Jul 29 02:34:19 lviv darkice[14297]: 29-Jul-2022 02:34:19 MultiThreadedConnector :: ThreadData :: threadFunction, now is (thread, priorit>
Jul 29 03:39:14 lviv systemd[1]: darkice.service: Main process exited, code=exited, status=1/FAILURE
Jul 29 03:39:14 lviv systemd[1]: darkice.service: Failed with result 'exit-code'.
Jul 29 03:39:31 lviv darkice[19387]: DarkIce 1.4 live audio streamer, http://code.google.com/p/darkice/
Jul 29 03:39:31 lviv darkice[19387]: Copyright (c) 2000-2007, Tyrell Hungary, http://tyrell.hu/
Jul 29 03:39:31 lviv darkice[19387]: Copyright (c) 2008-2013, Akos Maroy and Rafael Diniz
Jul 29 03:39:31 lviv darkice[19387]: This is free software, and you are welcome to redistribute it
```

This is `/etc/systemd/system/darkice.service` on that system. As a side note, `-v 6` seems to have no effect.

```text
[Unit]
Description=darkice
Wants=network.target
After=network.target
StartLimitIntervalSec=0

[Service]
Type=exec
#ExecStart=/usr/bin/darkice -v 6 -c /etc/darkice-kszt-ctaf.cfg
ExecStart=/home/jacobmarble/projects/darkice/darkice/trunk/src/darkice -v 6 -c /etc/darkice-kszt-ctaf.cfg
Restart=always
RestartSec=3
User=darkice
CPUSchedulingPolicy=fifo
CPUSchedulingPriority=4

StandardOutput=journal

[Install]
WantedBy=default.target
```

**Comment by jacobmarble** [comment]
Clearly, the error reported catch block in `main()` should always be succeeded by a process exit with non-zero status code. I feel comfortable opening a pull request to add `_Exit(1)` there, so I'll work on that next.

The alternative:

Try to recover the state of the handler without exiting the process. Even if that works, the process still needs to learn to exit expediently when the recovery attempt fails. `snd_pcm_recover()` won't resolve my particular issue, so one would need to experiment with discarding and re-opening the handle.

```text
snd_pcm_recover()
...
Recover the stream state from an error or suspend.
...
This functions handles -EINTR (interrupted system call), -EPIPE (overrun or underrun) and -ESTRPIPE (stream is suspended) error codes trying to prepare given stream for next I/O.
```
