### ISSUE TITLE
missing `darkice-1.5.tar.gz` release tarball

### ISSUE THREAD

**Issue by chenrui333** [rafael2k/darkice#194]
👋 looks like `darkice-1.5.tar.gz` release tarball is missing for the most recent 1.5 release.  Raise this issue for some awareness. Thanks!

**Comment by Polynomial-C** [comment]
Hello. I second this request. Thanks.

**Comment by rafael2k** [comment]
https://codeload.github.com/rafael2k/darkice/tar.gz/refs/tags/v1.5
?

**Comment by Polynomial-C** [comment]
> https://codeload.github.com/rafael2k/darkice/tar.gz/refs/tags/v1.5 ?

Please look into the tarball you just linked to and then look into the https://github.com/rafael2k/darkice/releases/download/v1.4/darkice-1.4.tar.gz tarball. The latter only contains darkice while the one you referred to contains also the deprecated gui and the website content.

**Comment by chenrui333** [comment]
<img width="809" alt="image" src="https://github.com/rafael2k/darkice/assets/1580956/faf94795-f3aa-45b6-bc91-26739469e0d1">
![image](https://github.com/rafael2k/darkice/assets/1580956/c5c76222-35fc-4d9c-aa52-48100f3346f7)

**Comment by chenrui333** [comment]
@rafael2k does that make sense?

**Comment by chenrui333** [comment]
ping @rafael2k

**Comment by chenrui333** [comment]
https://github.com/Homebrew/homebrew-core/pull/177256
