### ISSUE TITLE
compiled fdk-aac 

### ISSUE THREAD

**Issue by 0d0a** [rafael2k/darkice#198]
with https://salsa.debian.org/multimedia-team/fdk-aac on raspberry pi400 running bookworm specifying aacp in darkice.cfg
mayybe this helps others

**Comment by rafael2k** [comment]
There are packages for it in the "non-free":
https://packages.debian.org/source/stable/fdk-aac

**Comment by rafael2k** [comment]
Most importantly - is AAC with fdk-aac working fine for you?

**Comment by 0d0a** [comment]
yes it is!

**Comment by rafael2k** [comment]
Cool!
Closing this issue.
